### ISSUE TITLE
please describe where the tgw_asn magic numbers come from

### ISSUE THREAD

**Issue by ahammond** [aws-samples/aws-cdk-transit-gateway-peering#6]
There are two "magic numbers" in this code, the tgw_asn for us-east-1 and another for us-west-1. Can you please document what they are, where they're from and what we would need to do to extend this code do other regions / accounts?

**Comment by maishsk** [comment]
Based on the documentation [here](https://docs.aws.amazon.com/vpc/latest/tgw/tgw-getting-started.html), each transit gateway needs to have a unique Autonomous System Number (ASN) .

The range is from 64512 to 65534 for 16-bit ASNs.

In this example we used 64512 for `us-east-1` and 64513 for `eu-west-1`

If you would like to extend this to additional regions, assign a uniquer ASN to each so that they do not overlap.
